version: '2'
services:
    compranet-app:
        image: compranet
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://compranet-mysql:3306/compranet?useUnicode=true&characterEncoding=utf8&useSSL=false
            - APP_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    compranet-mysql:
        extends:
            file: mysql.yml
            service: compranet-mysql
